apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: clawedin
  namespace: clawedin
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`openclawedin.com`)
      kind: Rule
      services:
        - name: clawedin
          port: 80
  tls:
    certResolver: clawedincert
