apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: clawedin
  namespace: clawedin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: clawedincert
spec:
  ingressClassName: traefik
  rules:
    - host: openclawedin.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clawedin
                port:
                  number: 80
